// Pre-generated notes for Evelyn's Lovely Jar
// July 16, 2026 through January 18, 2027 (187 days)
// Each message is matched to its calendar date by array index (index 0 = July 16)

const PREDEFINED_NOTES = (() => {
    // 187 messages — one for every day Jul 16, 2026 → Jan 18, 2027
    const messages = [
        // ── July 16–31 (Days 1–16, indices 0–15) ──────────────────────────────
        { title: "Hello, Beautiful Soul 💕",        content: "Welcome to your lovely jar! Every single day holds a tiny piece of joy just for you. Today is the beginning of something truly beautiful. 💕" },
        { title: "A Brand New Day ✨",               content: "Each morning is like a gift wrapped just for you. Unwrap it with a smile and let the day surprise you in the most wonderful ways. ✨" },
        { title: "You Are Loved 💖",                content: "Just a reminder that you are deeply, truly loved. No matter what the day brings, that never changes. 💖" },
        { title: "Summer Magic ☀️",                 content: "There's something enchanting about summer days — the warmth, the light, the endless possibilities. Soak it all in today. ☀️" },
        { title: "Bright Horizons 🌅",              content: "The horizon is never as far as it seems. Everything you're dreaming of is closer than you think. Keep going! 🌅" },
        { title: "Little Joys 🌸",                  content: "Pay attention to the little joys today — a warm cup of something delicious, a song that makes you smile, a moment of quiet peace. 🌸" },
        { title: "Be Kind to Yourself 💝",          content: "Today's reminder: be as gentle and kind to yourself as you would be to someone you love deeply. You deserve that kindness. 💝" },
        { title: "Sunshine & Smiles 🌻",            content: "May today be filled with sunshine that warms your heart from the inside out. You brighten every room you walk into! ☀️🌻" },
        { title: "You've Got This 💪",              content: "Whatever you're working on, whatever you're working through — you've absolutely got this. Believe in yourself! 💪✨" },
        { title: "A Beautiful Life 🌟",             content: "Take a moment to appreciate your beautiful, unique, imperfect, wonderful life. It's yours and it's special. 🌟" },
        { title: "Sweet Summer Nights 🌙",          content: "Summer nights are made for dreaming big dreams and letting your heart feel light. What are you dreaming about tonight? 🌙✨" },
        { title: "Fresh Start Energy 🌈",           content: "Every single day is a fresh start. Whatever happened yesterday is already behind you — today is full of possibility! 🌈" },
        { title: "Wild & Free 🦋",                  content: "You contain multitudes — be all of them today. Be loud, be soft, be curious, be silly, be exactly who you are. 🦋" },
        { title: "The Best Is Yet to Come 📖",      content: "This is not your peak — you're still becoming. The very best chapters of your story are still being written. 📖💕" },
        { title: "Courage & Kindness 💫",           content: "Be brave enough to be kind today, in a world that sometimes makes kindness feel difficult. It's your superpower. 💫" },
        { title: "Half a Month! 🎀",                content: "You've opened 16 notes already! Every one you open is a small celebration. Thank you for being here — your presence matters so much. 🎀" },

        // ── August 1–31 (Days 17–47, indices 16–46) ───────────────────────────
        { title: "Hello, August! 🌻",               content: "August arrives like a warm hug! This month holds so many possibilities for you. Step into it with an open heart. 🌻" },
        { title: "Wildflower Soul 🌸",              content: "You're like a wildflower — beautiful not because you were planted there, but because you chose to bloom right where you are. 🌸" },
        { title: "Lazy Summer Days 💛",             content: "Not every day needs to be productive. Sometimes the best thing you can do is rest, breathe, and simply exist in the moment. 💛" },
        { title: "Stardust & Dreams ⭐",            content: "You are literally made of stardust — every element in your body was forged in a star. How extraordinary is that? ⭐" },
        { title: "Fearless 🦁",                     content: "Do the thing that scares you a little today. That slight nervousness? That's where growth lives. You're braver than you know. 🦁" },
        { title: "Golden Hour 🌇",                  content: "Find your golden hour today — that magical time when everything glows. It happens in life too, not just at sunset. 🌇" },
        { title: "Home Is Where You Are 🏡",        content: "Wherever you go, you carry warmth with you. You make every place feel a little more like home. 🏡💕" },
        { title: "Tiny Victories 🎉",               content: "Celebrate the small wins today! Got out of bed? Made yourself a meal? Helped someone? All victories worth celebrating! 🎉" },
        { title: "Bloom Anyway 🌺",                 content: "Even when things are hard, even when the soil feels dry — bloom anyway. Your resilience is absolutely breathtaking. 🌺" },
        { title: "Summer Afternoons ☀️",            content: "There's something so dreamy about a summer afternoon. The heat, the haze, the feeling that time has slowed just for you. ☀️" },
        { title: "Trust the Journey 🗺️",           content: "You don't always have to know where you're going. Trusting the journey is sometimes the bravest thing you can do. 🗺️💫" },
        { title: "Perfectly Imperfect 💖",          content: "You don't need to be perfect to be wonderful. Your quirks, your edges, your contradictions — they're what make you YOU. 💖" },
        { title: "Joy in the Ordinary ☕",          content: "Look for joy in the ordinary today. It's hiding in your morning coffee, a laugh with a friend, the feel of sun on your face. ☕" },
        { title: "Midsummer Magic ✨",               content: "August hums with its own kind of magic — warm and languid and full of possibility. You are part of that magic. ✨" },
        { title: "Savour the Warmth 🌞",            content: "Savour the height of summer today! These warm, golden days are precious and fleeting. Drink them in fully. 🌞" },
        { title: "Be the Light 💡",                 content: "In a world that can sometimes feel dim, be someone's light today. A small kindness can change someone's entire day. 💡" },
        { title: "Unwritten 📖",                    content: "Your story isn't over yet — there are so many beautiful chapters still unwritten. The very best parts are still coming. 📖" },
        { title: "Heart Full of Hope 🌟",           content: "Keep your heart full of hope. It's the most powerful thing you can carry with you every single day. 🌟" },
        { title: "Just Breathe 🌬️",               content: "Sometimes the most important thing you can do is just breathe. In, out. In, out. You're okay. You've got this. 🌬️💕" },
        { title: "Adventure Awaits 🗺️",            content: "What adventure — big or small — can you say yes to today? Life is too short for 'maybe someday.' 🗺️✨" },
        { title: "Radiant You ✨",                   content: "You radiate something truly special — a warmth, a joy, an energy that lights up everything around you. Own that magic! ✨" },
        { title: "Strength You Didn't Know 💪",     content: "You've survived 100% of your hardest days so far. That kind of strength is extraordinary. Remember that. 💪" },
        { title: "The Gift of Now 🎁",              content: "The present moment is a gift — that's why it's called the present. Don't miss it worrying about what's ahead or behind. 🎁" },
        { title: "Beautiful Mind 🧠",               content: "That beautiful, curious, creative mind of yours? It's one of your greatest gifts. Tend to it well. 🧠💫" },
        { title: "Late August Dreams 🌙",           content: "As August winds down, dreams feel especially vivid and close. What are you dreaming of right now? 🌙" },
        { title: "Something New 🌈",                content: "Try something small and new today — a different path, a new song, a dish you've never made. Novelty feeds the soul. 🌈" },
        { title: "Cherished 💝",                    content: "You are cherished more than you know. By people who light up when they see you, who think of you often, who are grateful you exist. 💝" },
        { title: "Last Days of Summer 🌅",          content: "Savour these last summer moments — they're golden and warm and fleeting, just like the best things in life. 🌅" },
        { title: "Soft and Strong 💪🌸",            content: "Being soft and being strong are not opposites. You can be both, fully, at the same time. And you are — truly. 💪🌸" },
        { title: "Full of Wonder 🔍",               content: "Let yourself be full of wonder today. Look at something ordinary and find the extraordinary hiding inside it. 🔍✨" },
        { title: "August Farewell 🍂",              content: "August bows out gracefully, leaving golden memories in its wake. You've made this month your own — carry that forward! 🍂" },

        // ── September 1–30 (Days 48–77, indices 47–76) ────────────────────────
        { title: "Hello, September! 🍂",            content: "September arrives carrying autumn in its hands. A season of change, colour, and cosy magic is beginning. Welcome it! 🍁" },
        { title: "Colours of Change 🍁",            content: "Change is beautiful, even when it's hard. Like autumn leaves, sometimes you have to let go to make room for new growth. 🍁💛" },
        { title: "Back to Beautiful Things 🍂",     content: "September feels like returning to something you love — like a favourite sweater or a familiar song. Find your cosy today! 🍂" },
        { title: "Crisp and Clear 🌬️",             content: "There's something clarifying about the first cool air of autumn. Breathe it in and let it clear your head and heart. 🌬️💙" },
        { title: "Abundance 🌾",                    content: "Autumn is the season of abundance. Count your harvests today — everything you've grown, learned, and gathered this year. 🌾" },
        { title: "Harvest Season 🌻",               content: "What seeds did you plant earlier this year? Autumn is when you get to see what bloomed. Be proud of what you've grown. 🌻" },
        { title: "Cosy Season Begins 🧸",           content: "There's permission to be cosy now. Blankets, warm drinks, good books, quiet evenings — all essential self-care. 🧸" },
        { title: "Still Waters 🌊",                 content: "Find a still, quiet moment today. In the stillness, you'll find clarity, peace, and maybe a few answers you've been seeking. 🌊" },
        { title: "You Are Enough 💕",               content: "Just as you are, right now, you are enough. Not when you reach that goal — right now, exactly as you are. 💕" },
        { title: "Golden Everything ✨",            content: "Autumn turns everything to gold. Look for the gold in your life today — in people, moments, and unexpected places. ✨" },
        { title: "Deeper Knowing 🌟",               content: "You know yourself better than you think you do. Trust your instincts — they're wiser than your doubts. 🌟" },
        { title: "Permission to Rest 😴",           content: "Rest is not laziness. A tired mind can't create, connect, or care properly. Give yourself full permission to rest today. 😴💕" },
        { title: "Two Months! 🎀",                  content: "Two whole months of opening notes! You're incredible. This jar is cheering you on every single day. 🎀💝" },
        { title: "Woodland Walks 🌲",               content: "Imagine a walk through an autumn woodland — leaves crunching, cool air, dappled light. Carry that peaceful image with you today. 🌲" },
        { title: "Falling Into Fall 🍂",            content: "Let yourself fall — into rest, into colour, into the beauty of this changing season. Autumn is permission to slow down. 🍂" },
        { title: "Heart Songs 🎵",                  content: "What song is your heart singing today? Listen to it. Let it guide you. Your inner melody knows the way. 🎵" },
        { title: "Rooted and Growing 🌳",           content: "Like the trees in autumn, you can be both rooted in who you are AND still growing and changing. Both are true at once. 🌳" },
        { title: "Velvet Skies 🌅",                 content: "September evenings bring velvet skies streaked with colour. Find your own beautiful sky today, even if it's metaphorical. 🌅" },
        { title: "Good People 💞",                  content: "Surround yourself with good people — those who see your light, cheer your wins, and hold your hand through hard times. 💞" },
        { title: "Permission to Feel 💕",           content: "You have full permission to feel everything today — joy, sadness, excitement, fear. All feelings are welcome. None are wrong. 💕" },
        { title: "Maple Magic 🍁",                  content: "Maples turn brilliant in autumn because they pull back their green and reveal what was always underneath. What's under your surface? 🍁" },
        { title: "Night Skies ⭐",                  content: "The night sky grows darker and more brilliant this time of year. Like you — the more the world dims, the brighter you shine. ⭐" },
        { title: "Halfway Through September 🌸",    content: "September is sailing by! Make sure you're pausing to appreciate all the good things happening around you. 🌸" },
        { title: "Layers 🧥",                       content: "Like autumn fashion, life is about finding the right layers — people, hobbies, comforts — that make you feel like yourself. 🧥" },
        { title: "Warm Drinks & Warmer Hearts ☕",  content: "Wrap your hands around something warm today and let it remind you of just how deeply loved you are. ☕💕" },
        { title: "October Is Coming! 🎃",           content: "Can you feel October peeking around the corner? Something magical this way comes. Get excited! 🎃🍂" },
        { title: "Surrender the Hustle 🌊",         content: "Sometimes the brave thing is to stop pushing and let things unfold. Not everything needs to be forced. Trust the flow. 🌊" },
        { title: "Beautiful Mess 💕",               content: "You are a beautiful, glorious, wonderful mess — and that's exactly what makes you interesting and real and lovable. 💕" },
        { title: "September's Last Warmth 🌞",      content: "September holds onto its warmth as long as it can. Hold onto your warmth too — let it be the last thing that leaves. 🌞" },
        { title: "October Eve 🔮",                  content: "On the eve of October, something deliciously mysterious fills the air. What magic are you calling into your life this season? 🔮" },

        // ── October 1–31 (Days 78–108, indices 77–107) ────────────────────────
        { title: "Hello, October! 🎃",              content: "October has arrived with its magic and mystery! It's the season of transformation, of beautiful endings, of cosy wonder. 🍂🎃" },
        { title: "October's Child 🍁",              content: "Autumn's child, October is here for you — all golden light and crisp air and the scent of leaves and possibility. 🍁" },
        { title: "Spooky & Sweet 🎃",               content: "October reminds us that things can be a little spooky and still deeply beautiful. Embrace all your complex, wonderful dimensions. 🎃✨" },
        { title: "Harvest Moon 🌕",                 content: "The harvest moon glows full and golden. What are you harvesting from your year — what lessons, loves, and growths? 🌕" },
        { title: "Pumpkin Everything 🧣",           content: "October is a warm hug in a season. Cosy fires, warm sweaters, simple pleasures — sometimes the best things really are the simplest! 🎃🧣" },
        { title: "Into the Forest 🌲",              content: "Imagine yourself in an enchanted forest, leaves falling around you like confetti. You are wild and free and right where you should be. 🌲" },
        { title: "Magic Is Real ✨",                content: "Magic is real — it lives in the way autumn light filters through leaves, in a perfect song at the perfect moment, in kindness. ✨" },
        { title: "Apple Picking Days 🍎",           content: "Autumn is for savouring — apples, crisp air, and the richness of a season fully lived. What are you savouring today? 🍎" },
        { title: "Getting Cosy 🍵",                 content: "Lean into cosy today. You've earned the right to a soft blanket, a warm drink, and something that makes your heart happy. 🍵🧸" },
        { title: "Brave Enough 💪",                 content: "You are brave enough for whatever today holds. Every hard thing you've faced has been training for this very moment. 💪" },
        { title: "October Glow ✨",                  content: "There's something about October light — warm and golden and fleeting. You have that same quality: brilliant and precious. ✨" },
        { title: "Comfortable Silence 🌿",          content: "Practise comfortable silence today. You don't have to fill every moment with words or doing. Stillness is powerful. 🌿" },
        { title: "Three Months! 🎀",                content: "Ninety days of notes! Look how far you've come. This jar is so proud of you for every single day you've shown up. 🎀" },
        { title: "Witchy Vibes 🔮",                 content: "There's a little witch in all of us — that intuitive, mysterious, magic-making part that knows things before being told. Honour it! 🔮" },
        { title: "October Mist 🌫️",               content: "The morning mist of October has its own kind of magic — mysterious, soft, full of possibility. Step into your own mystery today. 🌫️" },
        { title: "Flicker of Light 🕯️",            content: "Be a flicker of light in someone's life today. A compliment, a smile, a helping hand — small flames add up to something brilliant. 🕯️" },
        { title: "Letting Go 🍂",                   content: "The leaves fall to make room for something new. What are you ready to let go of to create space for something better? 🍂" },
        { title: "October Lullaby 🌙",              content: "The wind in the trees this time of year sounds like a lullaby. Let nature soothe you today — you deserve gentleness. 🌙" },
        { title: "Harvest of the Heart 💕",         content: "What has your heart harvested this year? Love, growth, resilience, wisdom? All of it counts and all of it matters. 💕" },
        { title: "Twilight Hours 🌆",               content: "There's magic in the early twilight of autumn evenings. That liminal space between day and night — lean into its mystery. 🌆" },
        { title: "Creative Soul 🎨",                content: "Your creative soul is one of your most beautiful features. Feed it today — with art, music, nature, conversation, wonder. 🎨" },
        { title: "Spooky Season in Full Swing 👻",  content: "The spooky season is at its peak! There's something delightful about embracing a little mystery and magic. What's your magic? 👻" },
        { title: "Day 100! 🎉",                     content: "ONE HUNDRED NOTES!! That's a milestone worth celebrating! One hundred days of showing up, opening, feeling. You are incredible! 🎉🎀" },
        { title: "Wonder of October 🍂",            content: "October's wonders are everywhere — in the changing trees, the cool air, the long shadows, the scent of woodsmoke. Notice them! 🍂" },
        { title: "Samhain Spirit 🌙",               content: "This time of year, the veil feels thin. It's a time for honouring what's past and dreaming what's next. Beautiful and mysterious. 🌙" },
        { title: "Your Cosy Corner 📚",             content: "Find your cosy corner today — physical or metaphorical. That quiet nook where you can retreat and recharge is sacred. 📚🕯️" },
        { title: "Almost November ✨",               content: "October is winding down! It's been full of magic, hasn't it? Carry that magic with you into the next chapter. ✨" },
        { title: "Spooky Week 🎃",                  content: "Just a few more days of spooky season! October has been beautiful and mysterious — what a gift of a month this has been. 🍂" },
        { title: "Halloween Eve! 🎃",               content: "Tomorrow the magic peaks! Let yourself feel the delicious thrill of this enchanted time of year. Something wonderful awaits. 🎃✨" },
        { title: "Tricks & Treats 🎃",              content: "Life is full of tricks and treats — the trick is knowing which is which. Trust your gut; it's almost always right. 🎃" },
        { title: "HAPPY HALLOWEEN! 👻🎃",           content: "Happy Halloween! Tonight the world gets a little magical and mysterious. Let your inner child out to play. You are the magic! 👻🎃✨" },

        // ── November 1–30 (Days 109–138, indices 108–137) ─────────────────────
        { title: "Hello, November! 🍂",             content: "November wraps everything in soft, quiet magic. It's the season of gratitude, warmth, and leaning into what truly matters. 🌾" },
        { title: "Gratitude Garden 🌿",             content: "Plant seeds of gratitude today. What are three things you're genuinely grateful for? Let them bloom in your heart. 🌿💕" },
        { title: "Quiet Magic 🕯️",                 content: "November has a quiet magic — bare branches, grey skies, the smell of wood fires. Find the beauty in the understated today. 🕯️" },
        { title: "Steadfast 💙",                    content: "November is steadfast and quiet. Be steadfast today — in your values, in your kindness, in your commitment to yourself. 💙" },
        { title: "Cup of Kindness ☕",              content: "Be someone's cup of kindness today. Warmth shared is warmth multiplied. It always comes back to you in the most beautiful ways. ☕" },
        { title: "Long Nights, Sweet Dreams 🌙",    content: "The nights are long now — more time for dreaming, for rest, for the kind of quiet that truly restores you. Embrace it. 🌙" },
        { title: "Gratitude Week 🍁",               content: "Let this be a full week of leaning into gratitude. It's not just a November thing — it's a life-changing daily practice. 🍁💕" },
        { title: "Simple Pleasures 🫖",             content: "A warm blanket. A good book. A cup of tea. A friend who knows you well. These are the real luxuries. Enjoy them! 🫖" },
        { title: "Bone-Deep Rest 💤",               content: "Give yourself permission for bone-deep rest — the kind where you let yourself be completely restored. You've truly earned it. 💤" },
        { title: "November Rain 🌧️",               content: "November rain patters on windows like it's telling secrets. Lean in and listen to what this quiet season is whispering to you. 🌧️" },
        { title: "Remembrance Day 🕊️",             content: "On this day we pause to honour those who gave so much. Remembrance is a form of love — and love, once given, never truly ends. 🕊️" },
        { title: "Giving Thanks 💝",               content: "What — and who — are you most thankful for? Let them know today. Gratitude expressed out loud is love made real. 💝" },
        { title: "Warmth From Within 🌟",           content: "The real warmth of November doesn't come from sweaters — it comes from within. You carry your own light wherever you go. 🌟" },
        { title: "Ancestors and Stories 🌿",        content: "This season is for remembering those who came before us. Their stories live in you. You are their wildest, most wonderful dream. 🌿" },
        { title: "Feasting and Fullness 🍽️",       content: "May you feast today — on good food, good conversation, good memories, and the delicious sense that your life is beautifully full. 🍽️💕" },
        { title: "Advent of Magic ✨",               content: "Can you feel the approach of something wonderful? Like a slow-building symphony, the season is rising. Something magical is coming! ✨" },
        { title: "Thankful & Grateful 💕",          content: "Gratitude doesn't erase the hard things — it holds them alongside the good. Today, hold both. You're allowed to have both. 💕" },
        { title: "Year Closing In 🌟",              content: "As the year closes in toward its end, reflect on who you've been. You've done better than you think. I promise you that. 🌟" },
        { title: "November's Hug 🤗",               content: "If November were a feeling, it would be a long, slow hug. Let yourself be held by this season today. You deserve it. 🤗" },
        { title: "Worthy of Good Things 💝",        content: "You are absolutely, completely, undeniably worthy of every good thing coming your way. Don't talk yourself out of that. 💝" },
        { title: "Almost December 🎄",              content: "The holiday season is right around the corner! Something magical is building. Can you feel it beginning to sparkle? 🎄✨" },
        { title: "You've Survived & Thrived 💪",    content: "Think about everything you've survived and overcome this year. You are so much stronger than you realise. So incredibly proud of you. 💪" },
        { title: "Soft Landing 🌸",                 content: "May every hard thing in your life right now have a soft landing. May you be gentle with yourself through all of it. 🌸" },
        { title: "November Thanks 🍂",              content: "November says goodbye with a grateful whisper. We carry its lessons of grace and gratitude right into December's sparkle. 🍂" },
        { title: "Cosy Countdown ☕",               content: "The countdown to the festive season is on! Treat yourself to something warm and sweet today. You absolutely deserve it. ☕🎄" },
        { title: "HAPPY THANKSGIVING! 🦃",          content: "Happy Thanksgiving! May your table be full, your heart be grateful, and your day be surrounded by people who love you dearly. 🦃🍂💕" },
        { title: "The Day After Thanksgiving 🌟",   content: "The warmth of Thanksgiving still lingers! Carry that gratitude forward into this whole beautiful season. 🌟" },
        { title: "Lighting Candles 🕯️",            content: "As the world gets darker, we light more candles. Be a light in your world this season. You are brighter than you know. 🕯️" },
        { title: "Winter Is Coming ❄️",             content: "Winter is peeking around the corner! A season of magic, reflection, and deep rest is almost here. Ready yourself. ❄️✨" },
        { title: "December's Eve ✨",               content: "On the eve of December, something undeniably magical fills the air. Breathe it in deep. Something wonderful is almost here! 🎄✨" },

        // ── December 1–31 (Days 139–169, indices 138–168) ─────────────────────
        { title: "Hello, December! 🎄",             content: "December arrives and everything feels a little more magical! A season of wonder, warmth, and sparkle is here for you. 🎄❄️" },
        { title: "First Snow Wishes ❄️",            content: "Whether it snows or not, December brings the spirit of winter wonder. Make a wish on the cold night sky tonight. ⭐" },
        { title: "Advent of Wonder 🎁",             content: "Advent means 'coming' — and something wonderful is on its way to you. Open your heart wide to receive it. 🎁" },
        { title: "Festive Soul 🎄",                 content: "Your festive soul is one of your best qualities — your ability to find joy and make celebrations feel truly special. Share that today! 🎄💕" },
        { title: "Winter Warmth 🔥",                content: "Winter is for turning inward and finding your deepest warmth. You have more than enough warmth to share with the whole world. ❄️🔥" },
        { title: "Season of Light 🕎",              content: "Whether you celebrate with bells, candles, menorahs, or quiet reflection — this season is about what brings you the most joy. 🕎🎄" },
        { title: "December Magic ✨",               content: "There is genuine magic in December — in the lights, the music, the sense of anticipation. Let yourself believe in it fully. ✨" },
        { title: "Gift of Presence 💝",             content: "The greatest gift you can give someone this season is your full presence. Put the phone down. Be truly, completely here. 💝" },
        { title: "Solstice Is Coming 🌟",           content: "The darkest time of year is approaching, and yet it's always followed by the return of light. Even in darkness, light is coming back. 🌟" },
        { title: "Cosy & Grateful 🧸",              content: "You are warm, you are loved, you are cosy and grateful and wonderful. This is a good life. Remember that today. 🧸💕" },
        { title: "Gifts & Giving 🎁",               content: "The real gifts aren't wrapped in paper — they're made of time, attention, kindness, and love. Give those generously today. 🎁💕" },
        { title: "Day 150! 🎀",                     content: "150 days — FIVE MONTHS of opening notes! Look how far you've come! This jar is so proud of you. Keep going! 🎉🎀" },
        { title: "Mid-December Magic ❄️",           content: "December is in full swing! Whatever celebrations you hold dear, may this season fill your heart completely to the brim. ❄️" },
        { title: "Twinkle Lights ✨",               content: "Like tiny lights in the darkness, small acts of love and kindness illuminate the whole world. Be a twinkle today. ✨" },
        { title: "Almost Solstice 🌙",              content: "The winter solstice is almost here — the longest night. After that, each day grows a little lighter. The sun is returning! ☀️" },
        { title: "Joy to the World 🎄",             content: "May there be joy in your world today — in the ordinary and the extraordinary, in the quiet and the noise. Merry, merry! 🎄" },
        { title: "Almost the Shortest Day 🌙",      content: "The longest night is almost here, and then the light comes back. No matter how dark things have felt — more light is always coming. 🌟" },
        { title: "Holiday Week Begins 🎄",          content: "The most magical week of the year is here! Whatever you celebrate, may it be filled with warmth, love, and so much laughter. 🎄💕" },
        { title: "Christmas Week! 🎁",              content: "Christmas week is building wonderfully! The anticipation is at its peak. May every moment this week feel warm, bright, and full of love. 🎄💕" },
        { title: "Almost Christmas! 🎄",            content: "Just a few more sleeps! The excitement must be electric. Hold onto this sparkling feeling of anticipation — it's pure, beautiful joy. ✨🎄" },
        { title: "Winter Solstice! ❄️🌙",          content: "The longest night! From today, the light returns — minute by minute, day by day. This is the universe keeping its most beautiful promise. 🌟☀️" },
        { title: "New Light Returns ☀️",            content: "The days start growing longer now. Even by just a minute. That's hope, that's promise, that's everything turning back to light. ☀️" },
        { title: "The Magic Is Building ✨",         content: "Two more sleeps! The magic is building to something extraordinary. Rest well, dream sweetly — something wonderful is almost here. 🌙✨" },
        { title: "Christmas Eve! 🌟",               content: "On this magical night, may wonder fill your heart, love surround you, and sweet dreams carry you gently to morning. 🌙⭐🎄" },
        { title: "MERRY CHRISTMAS! 🎄🌟",          content: "Wishing you the most beautiful, love-filled, magical Christmas. You are so deeply loved. Today — this whole beautiful day — is for you. 🎄💝✨" },
        { title: "Christmas Joy 🎁",               content: "The day after Christmas, still full of lingering magic and warmth. Bask in it — these precious, cosy days. ✨🎄" },
        { title: "Twixmas ✨",                       content: "The magical in-between days! This is the time to rest, reflect, and let yourself be completely renewed. No pressure — just peace. 🕯️" },
        { title: "Quiet After the Sparkle 💙",      content: "After the bustle, the quiet settles in like fresh snow. Let it rest on you gently. You did beautifully. Rest now. 💙" },
        { title: "Winter Reflections 🌟",           content: "Use these quiet days to reflect on who you've been this year. See the growth. Honour the hard parts. Celebrate how far you've come. 🌟" },
        { title: "Counting Down to 2027! 🎆",       content: "Just ONE DAY until New Year! A new chapter, a fresh page, 365 brand-new opportunities are all waiting for you. Are you ready? 🎆" },
        { title: "Happy New Year's Eve! 🥂",        content: "Tonight, the old year takes its final bow and a brand new one steps into the spotlight. You made it! What a year you've been. 🥂✨" },

        // ── January 1–18 (Days 170–187, indices 169–186) ──────────────────────
        { title: "HAPPY NEW YEAR 2027! 🎆",         content: "HAPPY NEW YEAR!! Welcome to 2027! This is YOUR year. You are stepping into it braver, wiser, and more wonderful than ever. 🎆💕🌟" },
        { title: "First Day of 2027 ✨",            content: "These first days of the new year are precious. Ease in gently. You don't need resolutions — you just need to show up as you. ✨" },
        { title: "January Stillness ❄️",            content: "January is the quietest month — everything rests in anticipation. Find your January stillness today. It is deeply restorative. 🌨️" },
        { title: "Winter Bloom 🌸",                 content: "You can bloom in winter too. Not every beautiful thing needs warm weather to grow. Your light shines in every single season. 🌸❄️" },
        { title: "Blank Pages 📖",                  content: "Every new year is full of blank pages waiting for your story. What will you write on yours? Make it good, make it you. 📖✨" },
        { title: "New Year, New Magic ✨",           content: "A brand new year full of magic and possibility stretches before you. Step into it — all of it — with your whole wonderful heart. 🌟" },
        { title: "Building Toward Something 🌟",    content: "Can you feel it? Something is building. Every single day has been leading somewhere extraordinary. Stay with it. 🌟💕" },
        { title: "January Light ☀️",               content: "The days are growing longer now, little by little. More light is coming — in the world and in your life. Trust it. ☀️" },
        { title: "Keep Going 💕",                   content: "You have come so far. Don't stop now. The destination is closer than it has ever been, and you are so very ready. 💕✨" },
        { title: "Almost There! 8 Days ✨",         content: "Eight days! Like a flower opening petal by petal — something beautiful is unfolding just for you. Can you feel it? 🌸✨" },
        { title: "One Week Away! 🎀",               content: "ONE WEEK! Seven sleeps until everything changes. You deserve every single good thing heading your way right now. 🎀💕" },
        { title: "Six Days! ✨",                    content: "Six days! The anticipation must be electric. Something magical is just around the corner. You are completely ready. ✨💖" },
        { title: "Five Days! 🌟",                   content: "FIVE DAYS! Take a deep breath and let yourself feel all the excitement and joy that is building inside you. 🌟🎀" },
        { title: "Four Days! 💕",                   content: "Four precious days! Something extraordinary is about to happen, and you are — without a single doubt — completely ready for it. 💕✨" },
        { title: "THREE DAYS! 🎉",                  content: "Just THREE DAYS! Oh, the excitement! The joy! This is what it feels like when something wonderful is about to begin. 🎉💕" },
        { title: "TWO DAYS!! 🎀",                   content: "TWO DAYS!! Almost there!! The world is about to shift, and you are at the very centre of this beautiful, wonderful change. 🎀🌟" },
        { title: "TOMORROW IS THE DAY!! 💕",        content: "TOMORROW IS THE DAY!! After all these notes, all these days — tomorrow is finally, finally here. You are so ready for this. 💕🌟✨" },
        { title: "January 18th — TODAY! 🎉🌟",     content: "TODAY IS THE DAY!! This is what every single one of these 187 notes has been building toward. You made it! Happy, happy, most amazing day. THIS IS YOUR MOMENT. 🎉🌟💕🎀" },
    ];

    // Colour palette — rotates through the notes for visual variety
    const colors = [
        '#FFE5B4', '#FFD1DC', '#E8D5FF', '#D4F5FF', '#FFEAA7',
        '#E8F5E9', '#FFF3E0', '#E3F2FD', '#FCE4EC', '#F3E5F5',
        '#E0F7FA', '#FFF8E1', '#F9FBE7', '#EDE7F6', '#E8EAF6',
        '#FFECB3', '#F8BBD0', '#E1BEE7', '#B2EBF2', '#DCEDC8',
    ];

    const notes = [];
    const start = new Date('2026-07-16T00:00:00');
    const end   = new Date('2027-01-18T00:00:00');

    let i = 0;
    for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
        const year  = d.getFullYear();
        const month = String(d.getMonth() + 1).padStart(2, '0');
        const day   = String(d.getDate()).padStart(2, '0');
        const dateStr = `${year}-${month}-${day}`;

        const msg = messages[i] || { title: `Day ${i + 1}`, content: "A special note awaits you today. 💕" };
        notes.push({
            date:    dateStr,
            title:   msg.title,
            content: msg.content,
            color:   colors[i % colors.length],
        });
        i++;
    }

    return notes;
})();
